apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: newd
  name: newd
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: newd
  type: NodePort
status:
  loadBalancer: {}
